services:
  db:
    container_name: postgres-mabuhay
    image: postgres:latest
    environment:
      POSTGRES_USER: theodenmelgar
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
    - db
    restart: unless-stopped

networks:
      db:
        driver: bridge
volumes:
  db: