### GET request for menu item
GET http://localhost:8080/menu-item/2/

### Send POST request with json body
POST http://localhost:8080/menu-item/
Content-Type: application/json

{
  "name": "Test",
  "half_tray_price": 70.0,
  "full_tray_price": 140.0,
  "image": "https://images.unsplash.com/photo-1756142754703-1c24f2d1fe9a?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDF8MHxmZWF0dXJlZC1waG90b3MtZmVlZHwxfHx8ZW58MHx8fHx8",
  "menuCategory": 4
}

### Send PUT request with json body
PUT http://localhost:8080/menu-item/
Content-Type: application/json

{
  "id": 5,
  "name": "Test",
  "visibility": "Public",
  "half_tray_price": 70.0,
  "full_tray_price": 140.0,
  "image": "https://images.unsplash.com/photo-1756142754703-1c24f2d1fe9a?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDF8MHxmZWF0dXJlZC1waG90b3MtZmVlZHwxfHx8ZW58MHx8fHx8",
  "menuCategory": 4
}

### Send DELETE request for menu item
DELETE http://localhost:8080/menu-item/6/

### GET request to menu category
GET http://localhost:8080/menu/

### POST request to create new menu category
POST http://localhost:8080/menu
Content-Type: application/json

{
  "name": "Fish",
  "order": 1
}

### DELETE request to delete menu category
DELETE http://localhost:8080/menu/3

### GET request to show all orders
GET http://localhost:8080/order/

### POST request to show all orders
POST http://localhost:8080/order/
Content-Type: application/json

{
  "orderItems": [
    {
      "menuItemId": 3,
      "half_tray_quantity": 2,
      "full_tray_quantity": 0
    },
    {
      "menuItemId": 2,
      "half_tray_quantity": 0,
      "full_tray_quantity": 1
    }
  ],
  "price": 280.00,
  "customer_name": "Jane Doe",
  "customer_phone_number": "+1-555-123-4567",
  "customer_email": "jane.doe@example.com",
  "delivery_time": "2025-09-25T18:30:00Z"
}

### POST request to create a user
POST http://localhost:8080/auth/register/
Content-Type: application/json

{
  "username": "theodenmelgar",
  "password": "mypassword",
  "email": "theodenmelgar@gmail.com"
}

### POST request to login
POST http://localhost:8080/auth/login/
Content-Type: application/json

{
  "username": "theodenmelgar",
  "password": "mypassword"
}
